---
- hosts: aws
  remote_user: ubuntu
  tasks:
    - name: pull image
      command: docker pull "{{image}}:{{tag}}"
      become: true
    - name: stop old container
      command: docker stop "old-generator"
      become: true
    - name: remove old container
      command: docker rm "old-generator"
      become: true
    - name: start new service container
      command: docker run -d -p "8091:8080" --name "old-generator" {{image}}:{{tag}}
      become: true