spring:
  datasource:
    url: jdbc:h2:mem:my_app;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS "DEMO_DB"\;SET SCHEMA DEMO_DB;
    driverClassName: org.h2.Driver
    schemas: demo_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
server:
  port: 9900